function gitcmd
    if test (count $argv) -eq 0
        echo ""
        echo "╭────────────────────────────────────────────────────────╮"
        echo "│                    GIT CHEAT SHEET                     │"
        echo "├────────────────────────────────────────────────────────┤"
        echo "│ status       Current changes                           │"
        echo "| collab       How to collab                             |"
        echo "│ add          Stage files                               │"
        echo "│ commit       Create commit                             │"
        echo "│ push         Upload commits                            │"
        echo "│ pull         Download + integrate changes              │"
        echo "│ fetch        Download remote changes only              │"
        echo "│ clone        Copy remote repository                    │"
        echo "│ diff         Compare changes                           │"
        echo "│ log          View commit history                       │"
        echo "│ branch       Create/list/delete branches               │"
        echo "│ switch       Change branch                             │"
        echo "│ merge        Merge branches                            │"
        echo "│ rebase       Reapply commits                           │"
        echo "│ stash        Temporarily save changes                  │"
        echo "│ restore      Restore files                             │"
        echo "│ reset        Undo staging/commits                      │"
        echo "│ revert       Safely undo a commit                      │"
        echo "│ remote       Manage remote repositories                │"
        echo "│ tag          Create/list tags                          │"
        echo "│ cherry-pick  Apply a specific commit                   │"
        echo "│ conflict     Resolve merge conflicts                   │"
        echo "│ undo         Common ways to undo things                │"
        echo "╰────────────────────────────────────────────────────────╯"
        echo ""
        echo "Usage: gitcmd <topic>"
        echo ""
        return
    end

    switch $argv[1]

        case status
            echo ""
            echo "git status"
            echo "──────────"
            echo "Use: See modified, staged and untracked files."
            echo ""
            echo "Examples:"
            echo "  git status"
            echo "  git status --short"
            echo ""
        
        case collab
            echo ""
            echo "git switch feature"
            echo "edit files"
            echo "git add ."
            echo 'git commit -m "message"'    
            echo "git push origin feature"
            echo "do pull request from github to master/main branch"
            echo "git switch master"
            echo "git pull origin master"
            echo "git switch feature"
            echo "git merge master"
            echo "git push origin feature"

        case add
            echo ""
            echo "git add"
            echo "───────"
            echo "Use: Stage changes before committing."
            echo ""
            echo "Examples:"
            echo "  git add file.cpp"
            echo "  git add file1.cpp file2.cpp"
            echo "  git add ."
            echo "  git add -A"
            echo ""

        case commit
            echo ""
            echo "git commit"
            echo "──────────"
            echo "Use: Save staged changes as a commit."
            echo ""
            echo "Examples:"
            echo '  git commit -m "fix bug"'
            echo "  git commit"
            echo "  git commit --amend"
            echo ""

        case push
            echo ""
            echo "git push"
            echo "────────"
            echo "Use: Upload local commits to a remote repository."
            echo ""
            echo "Examples:"
            echo "  git push"
            echo "  git push origin main"
            echo "  git push -u origin feature"
            echo ""

        case pull
            echo ""
            echo "git pull"
            echo "────────"
            echo "Use: Download remote changes and integrate them."
            echo ""
            echo "Examples:"
            echo "  git pull"
            echo "  git pull origin main"
            echo "  git pull --rebase"
            echo ""

        case fetch
            echo ""
            echo "git fetch"
            echo "─────────"
            echo "Use: Download remote information WITHOUT changing your files."
            echo ""
            echo "Examples:"
            echo "  git fetch"
            echo "  git fetch origin"
            echo "  git fetch --all"
            echo ""

        case clone
            echo ""
            echo "git clone"
            echo "─────────"
            echo "Use: Download an entire remote repository."
            echo ""
            echo "Syntax:"
            echo "  git clone <url>"
            echo ""
            echo "Example:"
            echo "  git clone https://github.com/user/repo.git"
            echo ""

        case diff
            echo ""
            echo "git diff"
            echo "────────"
            echo "Use: Compare changes."
            echo ""
            echo "Examples:"
            echo "  git diff"
            echo "      Unstaged changes"
            echo ""
            echo "  git diff file.cpp"
            echo "      Changes in one file"
            echo ""
            echo "  git diff HEAD"
            echo "      All changes since last commit"
            echo ""
            echo "  git diff HEAD~1 HEAD"
            echo "      Compare two commits"
            echo ""
            echo "  git diff branchA..branchB"
            echo "      Compare two branches"
            echo ""
            echo "  git diff commitA..commitB"
            echo "      Compare two commits"
            echo ""

        case log
            echo ""
            echo "git log"
            echo "───────"
            echo "Use: View commit history."
            echo ""
            echo "Examples:"
            echo "  git log"
            echo "  git log --oneline"
            echo "  git log --oneline --graph --all"
            echo "  git log -5"
            echo ""

        case branch
            echo ""
            echo "git branch"
            echo "──────────"
            echo "Use: List, create or delete branches."
            echo ""
            echo "Examples:"
            echo "  git branch"
            echo "  git branch feature"
            echo "  git branch -d feature"
            echo "  git branch -D feature"
            echo "  git branch -a"
            echo ""

        case switch
            echo ""
            echo "git switch"
            echo "──────────"
            echo "Use: Switch branches."
            echo ""
            echo "Examples:"
            echo "  git switch main"
            echo "  git switch feature"
            echo "  git switch -c new-feature"
            echo ""

        case merge
            echo ""
            echo "git merge"
            echo "─────────"
            echo "Use: Combine another branch into your current branch."
            echo ""
            echo "Example:"
            echo "  git switch main"
            echo "  git merge feature"
            echo ""
            echo "If conflicts occur:"
            echo "  Fix files"
            echo "  git add <files>"
            echo "  git commit"
            echo ""

        case rebase
            echo ""
            echo "git rebase"
            echo "──────────"
            echo "Use: Move/reapply commits on top of another branch."
            echo ""
            echo "Examples:"
            echo "  git switch feature"
            echo "  git rebase main"
            echo ""
            echo "Interactive:"
            echo "  git rebase -i HEAD~3"
            echo ""
            echo "Useful for cleaning commit history."
            echo ""

        case stash
            echo ""
            echo "git stash"
            echo "─────────"
            echo "Use: Temporarily save uncommitted changes."
            echo ""
            echo "Examples:"
            echo "  git stash"
            echo "  git stash push -m \"work in progress\""
            echo "  git stash list"
            echo "  git stash pop"
            echo "  git stash apply"
            echo "  git stash drop"
            echo ""

        case restore
            echo ""
            echo "git restore"
            echo "───────────"
            echo "Use: Restore files from another state."
            echo ""
            echo "Examples:"
            echo "  git restore file.cpp"
            echo "      Discard unstaged changes"
            echo ""
            echo "  git restore --staged file.cpp"
            echo "      Unstage a file"
            echo ""
            echo "  git restore --source=HEAD file.cpp"
            echo "      Restore from last commit"
            echo ""

        case reset
            echo ""
            echo "git reset"
            echo "─────────"
            echo "Use: Move HEAD and/or change the staging area."
            echo ""
            echo "Examples:"
            echo "  git reset file.cpp"
            echo "      Unstage file, keep changes"
            echo ""
            echo "  git reset"
            echo "      Unstage everything"
            echo ""
            echo "  git reset --soft HEAD~1"
            echo "      Undo commit, keep changes staged"
            echo ""
            echo "  git reset HEAD~1"
            echo "      Undo commit, keep changes unstaged"
            echo ""
            echo "  git reset --hard HEAD~1"
            echo "      Undo commit AND discard changes"
            echo ""
            echo "⚠ WARNING: --hard can permanently destroy uncommitted work."
            echo ""

        case revert
            echo ""
            echo "git revert"
            echo "──────────"
            echo "Use: Safely undo an existing commit by creating a NEW commit."
            echo ""
            echo "Syntax:"
            echo "  git revert <commit>"
            echo ""
            echo "Example:"
            echo "  git revert a1b2c3d"
            echo ""
            echo "Usually preferred for commits already pushed/shared."
            echo ""

        case remote
            echo ""
            echo "git remote"
            echo "──────────"
            echo "Use: Manage remote repositories."
            echo ""
            echo "Examples:"
            echo "  git remote -v"
            echo "  git remote add origin <url>"
            echo "  git remote remove origin"
            echo "  git remote set-url origin <url>"
            echo ""

        case tag
            echo ""
            echo "git tag"
            echo "───────"
            echo "Use: Mark specific commits, often for releases."
            echo ""
            echo "Examples:"
            echo "  git tag"
            echo "  git tag v1.0.0"
            echo "  git tag -a v1.0.0 -m \"Version 1.0.0\""
            echo "  git push origin v1.0.0"
            echo "  git push --tags"
            echo ""

        case cherry-pick
            echo ""
            echo "git cherry-pick"
            echo "───────────────"
            echo "Use: Apply a specific commit from another branch."
            echo ""
            echo "Syntax:"
            echo "  git cherry-pick <commit>"
            echo ""
            echo "Example:"
            echo "  git cherry-pick a1b2c3d"
            echo ""

        case conflict
            echo ""
            echo "GIT CONFLICTS"
            echo "─────────────"
            echo "When merge/rebase produces conflicts:"
            echo ""
            echo "1. Check conflicts:"
            echo "   git status"
            echo ""
            echo "2. Open conflicted files and fix:"
            echo "   <<<<<<< HEAD"
            echo "   your changes"
            echo "   ======="
            echo "   incoming changes"
            echo "   >>>>>>> branch"
            echo ""
            echo "3. Stage fixed files:"
            echo "   git add <file>"
            echo ""
            echo "4. Finish merge:"
            echo "   git commit"
            echo ""
            echo "For rebase:"
            echo "   git add <file>"
            echo "   git rebase --continue"
            echo ""
            echo "Abort:"
            echo "   git merge --abort"
            echo "   git rebase --abort"
            echo ""

        case undo
            echo ""
            echo "COMMON GIT UNDO COMMANDS"
            echo "────────────────────────"
            echo ""
            echo "Unstage file:"
            echo "  git restore --staged file"
            echo ""
            echo "Discard changes in file:"
            echo "  git restore file"
            echo ""
            echo "Undo last commit, keep changes:"
            echo "  git reset HEAD~1"
            echo ""
            echo "Undo last commit, keep changes staged:"
            echo "  git reset --soft HEAD~1"
            echo ""
            echo "Undo last commit and DELETE changes:"
            echo "  git reset --hard HEAD~1"
            echo ""
            echo "Undo a pushed/shared commit:"
            echo "  git revert <commit>"
            echo ""

        case '*'
            echo ""
            echo "Unknown topic: $argv[1]"
            echo "Run 'gitcmd' to see available topics."
            echo ""
    end
end

